CREATE DATABASE IF NOT EXISTS `usersdb`;
USE `usersdb`;

DROP TABLE IF EXISTS `PEDIDOS`;
DROP TABLE IF EXISTS `CARRITO`;
DROP TABLE IF EXISTS `PRODUCTOS`;
DROP TABLE IF EXISTS `VENDEDORES`;
DROP TABLE IF EXISTS `USUARIO`;

CREATE TABLE USUARIO(
idUsuario int (10) ,
nombre VARCHAR (255) NOT NULL,
apellido1 VARCHAR (255) NOT NULL,
username VARCHAR (255) NOT NULL,
email VARCHAR (255) NOT NULL,
contrasena VARCHAR (255) NOT NULL,
direccion VARCHAR (255) NOT NULL,

CONSTRAINT PK_USUARIO PRIMARY KEY (email)
);

CREATE TABLE VENDEDORES(
idUsuario VARCHAR (255) NOT NULL,
username VARCHAR (255) NOT NULL,

CONSTRAINT PK_VENDEDORES PRIMARY KEY (username),
CONSTRAINT FK_VENDEDORES FOREIGN KEY (username) REFERENCES USUARIO (email) ON DELETE CASCADE
);

CREATE TABLE PRODUCTOS(
idProducto int (10) auto_increment,
nombreProducto VARCHAR (255) NOT NULL,
marca VARCHAR (255) NOT NULL,
talla VARCHAR (255) NOT NULL,
descripcionbreve VARCHAR (255) NOT NULL,
precio VARCHAR (255) NOT NULL,
cantidad int (10) NOT NULL,
idUsuario VARCHAR (255) NOT NULL,
imagen BLOB(1000000000) NOT NULL,

CONSTRAINT PK_PRODUCTOS PRIMARY KEY (idProducto),
CONSTRAINT FK_PRODUCTOS FOREIGN KEY (idUsuario) REFERENCES VENDEDORES (username) ON DELETE CASCADE
);

CREATE TABLE CARRITO(
idUsuario VARCHAR (255) NOT NULL,
idCarrito int (100) NOT NULL,
idProducto int (100) NOT NULL,
cantidad int (100) NOT NULL,

CONSTRAINT PK_CARRITO PRIMARY KEY (idUsuario, idCarrito, idProducto),
CONSTRAINT FK_CARRITO FOREIGN KEY (idProducto) REFERENCES PRODUCTOS (idProducto) ON DELETE CASCADE,
CONSTRAINT FK_CARRITO2 FOREIGN KEY (idUsuario) REFERENCES USUARIO (email) ON DELETE CASCADE ON UPDATE CASCADE
); 

CREATE TABLE PEDIDOS(
idPedido int (10) NOT NULL,
idUsuario VARCHAR (255) NOT NULL,
idCarrito int (10) NOT NULL,
fecha DATE NOT NULL,
estado VARCHAR (1) NOT NULL,

CONSTRAINT PK_PEDIDOS PRIMARY KEY (idPedido),
CONSTRAINT UK_PEDIDOS UNIQUE (idUsuario, idCarrito),
CONSTRAINT FK_PEDIDOS FOREIGN KEY (idUsuario, idCarrito) REFERENCES CARRITO (idUsuario, idCarrito) ON DELETE NO ACTION ON UPDATE CASCADE
);